UPDATE `flights` SET `ORIGINAIRPORTCODE`='EAR',`ORIGAIRPORTNAME`='Humans United Space Station',`ORIGINCITYNAME`='Earth' WHERE `ORIGINAIRPORTCODE`='ORD';
UPDATE `flights` SET `DESTAIRPORTCODE`='EAR',`DESTAIRPORTNAME`='Humans United Space Station',`DESTCITYNAME`='Earth' WHERE `DESTAIRPORTCODE`='ORD';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='MAR',`ORIGAIRPORTNAME`='Musk Interplanetary Space Station',`ORIGINCITYNAME`='Mars' WHERE `ORIGINAIRPORTCODE`='DEN';
UPDATE `flights` SET `DESTAIRPORTCODE`='MAR',`DESTAIRPORTNAME`='Musk Interplanetary Space Station',`DESTCITYNAME`='Mars' WHERE `DESTAIRPORTCODE`='DEN';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='MOO',`ORIGAIRPORTNAME`='Armstrong Space Station',`ORIGINCITYNAME`='Moon' WHERE `ORIGINAIRPORTCODE`='IAH';
UPDATE `flights` SET `DESTAIRPORTCODE`='MOO',`DESTAIRPORTNAME`='Armstrong Space Station',`DESTCITYNAME`='Moon' WHERE `DESTAIRPORTCODE`='IAH';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='VEN',`ORIGAIRPORTNAME`='Galileo Space Station',`ORIGINCITYNAME`='Venus' WHERE `ORIGINAIRPORTCODE`='SFO';
UPDATE `flights` SET `DESTAIRPORTCODE`='VEN',`DESTAIRPORTNAME`='Galileo Space Station',`DESTCITYNAME`='Venus' WHERE `DESTAIRPORTCODE`='SFO';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='JUP',`ORIGAIRPORTNAME`='IO Space Station',`ORIGINCITYNAME`='Jupiter' WHERE `ORIGINAIRPORTCODE`='IAD';
UPDATE `flights` SET `DESTAIRPORTCODE`='JUP',`DESTAIRPORTNAME`='IO Space Station',`DESTCITYNAME`='Jupiter' WHERE `DESTAIRPORTCODE`='IAD';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='SAT',`ORIGAIRPORTNAME`='Dione Space Station',`ORIGINCITYNAME`='Saturn' WHERE `ORIGINAIRPORTCODE`='LAX';
UPDATE `flights` SET `DESTAIRPORTCODE`='SAT',`DESTAIRPORTNAME`='Dione Space Station',`DESTCITYNAME`='Saturn' WHERE `DESTAIRPORTCODE`='LAX';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='MER',`ORIGAIRPORTNAME`='Mariner 10 Space Station',`ORIGINCITYNAME`='Mercury' WHERE `ORIGINAIRPORTCODE`='EWR';
UPDATE `flights` SET `DESTAIRPORTCODE`='MER',`DESTAIRPORTNAME`='Mariner 10 Station',`DESTCITYNAME`='Mercury' WHERE `DESTAIRPORTCODE`='EWR';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='NPT',`ORIGAIRPORTNAME`='Triton Space Station',`ORIGINCITYNAME`='Neptune' WHERE `ORIGINAIRPORTCODE`='MCO';
UPDATE `flights` SET `DESTAIRPORTCODE`='NPT',`DESTAIRPORTNAME`='Triton Space Station',`DESTCITYNAME`='Neptune' WHERE `DESTAIRPORTCODE`='MCO';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='URA',`ORIGAIRPORTNAME`='Voyager II Space Station',`ORIGINCITYNAME`='Uranus' WHERE `ORIGINAIRPORTCODE`='CLE';
UPDATE `flights` SET `DESTAIRPORTCODE`='URA',`DESTAIRPORTNAME`='Voyager II Space Station',`DESTCITYNAME`='Uranus' WHERE `DESTAIRPORTCODE`='CLE';

UPDATE `flights` SET `ORIGINAIRPORTCODE`='PLT',`ORIGAIRPORTNAME`='Ronald Ekers Space Station',`ORIGINCITYNAME`='Pluto' WHERE `ORIGINAIRPORTCODE`='SEA';
UPDATE `flights` SET `DESTAIRPORTCODE`='PLT',`DESTAIRPORTNAME`='Ronald Ekers Space Station',`DESTCITYNAME`='Pluto' WHERE `DESTAIRPORTCODE`='SEA';